version: "3.9"

services:
  report:
    build: .
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - EMAIL_SENDER=${EMAIL_SENDER}
      - EMAIL_PASSWORD=${EMAIL_PASSWORD}
  database:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: stori-card
    ports:
      - 5433:5432
