version: "3.9"

services:
  report:
    build: .
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@database:5432/stori-card
      - EMAIL_SENDER=${EMAIL_SENDER}
      - EMAIL_PASSWORD=${EMAIL_PASSWORD}
    volumes:
      - ./tx_files:/app/tx_files
    depends_on:
      - database

  database:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: stori-card
    ports:
      - 5433:5432
