"""Add created_at timestamp to base model

Revision ID: 53d4d5b9d2cb
Revises: 28e627756e66
Create Date: 2025-07-04 16:36:49.802652

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "53d4d5b9d2cb"
down_revision = "28e627756e66"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "transactions",
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("transactions", "created_at")
    # ### end Alembic commands ###
